//
//  KeyMapper.swift
//  HappyHackingKeystroke
//
//  Created by Oliver Le on 10/8/24.
//

import Foundation

final class KeyMapper {
//    58 => Key::Alt,
//           61 => Key::AltGr,
//           51 => Key::Backspace,
//           57 => Key::CapsLock,
//           59 => Key::ControlLeft,
//           62 => Key::ControlRight,
//           125 => Key::DownArrow,
//           53 => Key::Escape,
//           122 => Key::F1,
//           109 => Key::F10,
//           103 => Key::F11,
//           111 => Key::F12,
//           120 => Key::F2,
//           99 => Key::F3,
//           118 => Key::F4,
//           96 => Key::F5,
//           97 => Key::F6,
//           98 => Key::F7,
//           100 => Key::F8,
//           101 => Key::F9,
//           63 => Key::Function,
//           123 => Key::LeftArrow,
//           55 => Key::MetaLeft,
//           54 => Key::MetaRight,
//           36 => Key::Return,
//           124 => Key::RightArrow,
//           56 => Key::ShiftLeft,
//           60 => Key::ShiftRight,
//           49 => Key::Space,
//           48 => Key::Tab,
//           126 => Key::UpArrow,
//           50 => Key::BackQuote,
//           18 => Key::Num1,
//           19 => Key::Num2,
//           20 => Key::Num3,
//           21 => Key::Num4,
//           23 => Key::Num5,
//           22 => Key::Num6,
//           26 => Key::Num7,
//           28 => Key::Num8,
//           25 => Key::Num9,
//           29 => Key::Num0,
//           27 => Key::Minus,
//           24 => Key::Equal,
//           12 => Key::KeyQ,
//           13 => Key::KeyW,
//           14 => Key::KeyE,
//           15 => Key::KeyR,
//           17 => Key::KeyT,
//           16 => Key::KeyY,
//           32 => Key::KeyU,
//           34 => Key::KeyI,
//           31 => Key::KeyO,
//           35 => Key::KeyP,
//           33 => Key::LeftBracket,
//           30 => Key::RightBracket,
//           0 => Key::KeyA,
//           1 => Key::KeyS,
//           2 => Key::KeyD,
//           3 => Key::KeyF,
//           5 => Key::KeyG,
//           4 => Key::KeyH,
//           38 => Key::KeyJ,
//           40 => Key::KeyK,
//           37 => Key::KeyL,
//           41 => Key::SemiColon,
//           39 => Key::Quote,
//           42 => Key::BackSlash,
//           6 => Key::KeyZ,
//           7 => Key::KeyX,
//           8 => Key::KeyC,
//           9 => Key::KeyV,
//           11 => Key::KeyB,
//           45 => Key::KeyN,
//           46 => Key::KeyM,
//           43 => Key::Comma,
//           47 => Key::Dot,
//           44 => Key::Slash,
//           _ => Key::Unknown(code.into()),
}

